server:
  port: 8081
spring:
  application:
    name: ms-clients

  datasource:
    url: jdbc:mysql://localhost:3306/ms_santiago?serverTimezone=UTC
    username: root
    password: mysql

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
