server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: ms-clients
          uri: http://localhost:8081
          predicates:
            - Path=/clients/**
        - id: ms-sales
          uri: http://localhost:8082
          predicates:
            - Path=/sales/**
        - id: ms-auth
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**
